package org.mendrugo.nica.codegen;

import org.junit.jupiter.api.Test;
import org.mendrugo.nica.asm.*;
import org.mendrugo.nica.parser.HotSpotDebugParser;
import org.mendrugo.nica.parser.PerfAnnotateParser;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ExplainedJavaGeneratorTest {

    @Test
    void x86GeneratesExplainedSource() throws IOException {
        var snippet = parseX86();
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedX86");
        assertFalse(source.isBlank());
        assertTrue(source.contains("public class ExplainedX86"));
    }

    @Test
    void x86ContainsSignExtByteHelper() throws IOException {
        var snippet = parseX86();
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedX86");
        assertTrue(source.contains("signExtByte"));
        assertTrue(source.contains("(byte) unsignedByte"));
    }

    @Test
    void x86ContainsHighLevelComputation() throws IOException {
        var snippet = parseX86();
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedX86");
        // Should explain the computation at a high level
        assertTrue(source.contains("Sign-extend") || source.contains("signExtByte"));
        assertTrue(source.contains("product") || source.contains("multiply"));
        assertTrue(source.contains("truncated") || source.contains("truncate"));
    }

    @Test
    void x86IsShorterThanLiteral() throws IOException {
        var snippet = parseX86();
        String literal = LiteralJavaGenerator.generate(snippet, "Literal");
        String explained = ExplainedJavaGenerator.generate(snippet, "Explained");
        assertTrue(explained.length() < literal.length(),
            "Explained (" + explained.length() + " chars) should be shorter than Literal (" +
            literal.length() + " chars)");
    }

    @Test
    void aarch64GeneratesExplainedSource() throws IOException {
        var snippet = parseAArch64();
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedAArch64");
        assertFalse(source.isBlank());
        assertTrue(source.contains("public class ExplainedAArch64"));
    }

    @Test
    void aarch64ContainsVectorizedComment() throws IOException {
        var snippet = parseAArch64();
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedAArch64");
        assertTrue(source.contains("NEON") || source.contains("Vectorized") || source.contains("vectorized"));
    }

    @Test
    void graalvmContainsBoundsCheckExplanation() throws IOException {
        var snippet = PerfAnnotateParser.parse(loadResource("perf-annotate-graalvm-x86.asm"));
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedGraalVM");
        assertTrue(source.contains("Objects.requireNonNull"));
        assertTrue(source.contains("Objects.checkIndex"));
        assertTrue(source.contains("bounds check"));
    }

    @Test
    void graalvmContainsMethodSignatureInHeader() throws IOException {
        var snippet = PerfAnnotateParser.parse(loadResource("perf-annotate-graalvm-x86.asm"));
        String source = ExplainedJavaGenerator.generate(snippet, "ExplainedGraalVM");
        assertTrue(source.contains("VanillaByteArrays"));
    }

    @Test
    void smallSnippetExplainedHasLoop() {
        var insns = List.of(
            insn("vpmovsxbd", reg("xmm0"), reg("ymm0")),
            insn("vpmovsxbd", reg("xmm1"), reg("ymm1")),
            insn("vpmulld", reg("ymm0"), reg("ymm1"), reg("ymm2")),
            insn("vpslld", imm(0x18), reg("ymm2"), reg("ymm2")),
            insn("vpsrad", imm(0x18), reg("ymm2"), reg("ymm2")),
            insn("vpxor", reg("ymm2"), reg("ymm0"), reg("ymm0"))
        );
        var snippet = new AssemblySnippet(Architecture.X86_64, insns);
        String source = ExplainedJavaGenerator.generate(snippet, "SmallExplained");

        assertTrue(source.contains("for (int i = 0;"));
        assertTrue(source.contains("signExtByte"));
        assertTrue(source.contains("product"));
        assertTrue(source.contains("truncated"));
    }

    @Test
    void containsNicaAttribution() throws IOException {
        var snippet = parseX86();
        String source = ExplainedJavaGenerator.generate(snippet, "Test");
        assertTrue(source.contains("Generated by Nica"));
    }

    // --- Helpers ---

    private AssemblySnippet parseX86() throws IOException {
        return HotSpotDebugParser.parse(loadResource("hotspot-debug-x86.asm"), Architecture.X86_64);
    }

    private AssemblySnippet parseAArch64() throws IOException {
        return HotSpotDebugParser.parse(loadResource("hotspot-debug-aarch64.asm"), Architecture.AARCH64);
    }

    private static Instruction insn(String mnemonic, Operand... ops) {
        return new Instruction(-1, mnemonic, List.of(ops),
            mnemonic + " " + String.join(", ", java.util.Arrays.stream(ops).map(Object::toString).toList()));
    }
    private static Operand.Register reg(String name) { return new Operand.Register(name); }
    private static Operand.Immediate imm(long value) { return new Operand.Immediate(value); }

    private static String loadResource(String name) throws IOException {
        try (var is = ExplainedJavaGeneratorTest.class.getResourceAsStream("/" + name)) {
            if (is == null) throw new IOException("Resource not found: " + name);
            return new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
