package org.mendrugo.nica.codegen;

import org.mendrugo.nica.asm.*;
import org.mendrugo.nica.ir.*;
import org.mendrugo.nica.recipe.*;

import java.util.*;

/**
 * Generates a high-level, readable Java class from an assembly snippet
 * by applying pattern recognition recipes.
 *
 * <p>Where recipes match, the output uses readable abstractions
 * (e.g., "signExtByte", "xorReduce"). Where no recipe matches,
 * falls back to the literal register-level translation.</p>
 *
 * <p>The generated code is runnable and must produce identical results
 * to the Literal view for the same inputs.</p>
 */
public final class ExplainedJavaGenerator {

    private ExplainedJavaGenerator() {}

    /**
     * Generate an explained Java source file from a parsed assembly snippet.
     *
     * @param snippet the parsed assembly
     * @param className the name for the generated class
     * @return the Java source code
     */
    public static String generate(AssemblySnippet snippet, String className) {
        var sb = new StringBuilder();

        // Header
        sb.append("/**\n");
        sb.append(" * Explained high-level Java translation of ").append(snippet.architecture()).append(" assembly.\n");
        if (snippet.blockInfo() != null)
            sb.append(" * Block: ").append(snippet.blockInfo()).append('\n');
        if (snippet.methodSignature() != null)
            sb.append(" * Method: ").append(snippet.methodSignature()).append('\n');
        sb.append(" *\n");
        sb.append(" * Generated by Nica — https://github.com/mendrugo/nica\n");
        sb.append(" */\n");
        sb.append("public class ").append(className).append(" {\n\n");

        // Detect architecture-specific patterns
        var boundsChecks = BoundsCheckRecipe.find(snippet);

        // Emit explained run method
        sb.append("    /**\n");
        sb.append("     * Execute the assembly computation (explained view).\n");
        sb.append("     *\n");
        if (!boundsChecks.isEmpty()) {
            sb.append("     * Recognized patterns:\n");
            for (var bc : boundsChecks) {
                sb.append("     *   - ").append(bc.explanation()).append('\n');
            }
        }
        sb.append("     */\n");

        switch (snippet.architecture()) {
            case X86_64 -> emitX86Explained(sb, snippet, boundsChecks);
            case AARCH64 -> emitAArch64Explained(sb, snippet);
        }

        sb.append("}\n");
        return sb.toString();
    }

    private static void emitX86Explained(StringBuilder sb, AssemblySnippet snippet,
                                          List<BoundsCheckRecipe.BoundsCheckMatch> boundsChecks) {
        // Determine input registers
        var inputRegs = collectInputRegisters(snippet);

        sb.append("    public static int[] run(");
        for (int i = 0; i < inputRegs.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("int[] ").append(inputRegs.get(i));
        }
        sb.append(") {\n");

        if (!boundsChecks.isEmpty()) {
            // GraalVM pattern: emit the bounds check explanation
            for (var bc : boundsChecks) {
                sb.append('\n');
                for (var line : bc.javaCode().split("\n")) {
                    sb.append("        ").append(line).append('\n');
                }
                sb.append('\n');
            }
            sb.append("        return null; // simplified — actual data load follows bounds check\n");
        } else {
            // SIMD computation pattern
            emitSimdExplained(sb, snippet, inputRegs);
        }

        sb.append("    }\n");

        // Helper methods
        sb.append('\n');
        sb.append("    /** Sign-extend a byte value (equivalent to vpmovsxbd / sshll). */\n");
        sb.append("    private static int signExtByte(int unsignedByte) {\n");
        sb.append("        return (byte) unsignedByte;\n");
        sb.append("    }\n");

        // Main method
        sb.append('\n');
        sb.append("    public static void main(String[] args) {\n");
        sb.append("        int[] a = {1, 255, 127, 128, 0, 2, 254, 64};\n");
        sb.append("        int[] b = {10, 20, 30, 40, 50, 60, 70, 80};\n");
        sb.append("        int[] result = run(a, b);\n");
        sb.append("        if (result != null) {\n");
        sb.append("            System.out.print(\"Result: [\");\n");
        sb.append("            for (int i = 0; i < result.length; i++) {\n");
        sb.append("                if (i > 0) System.out.print(\", \");\n");
        sb.append("                System.out.print(result[i]);\n");
        sb.append("            }\n");
        sb.append("            System.out.println(\"]\");\n");
        sb.append("        }\n");
        sb.append("    }\n");
    }

    private static void emitSimdExplained(StringBuilder sb, AssemblySnippet snippet,
                                           List<String> inputRegs) {
        int lanes = 8; // x86 AVX2
        sb.append("        // Vectorized computation over ").append(lanes).append(" SIMD lanes\n");
        sb.append("        int[] result = new int[").append(lanes).append("];\n\n");
        sb.append("        for (int i = 0; i < ").append(lanes).append("; i++) {\n");

        // Analyze the instruction sequence to determine the computation
        boolean hasMul = snippet.instructions().stream().anyMatch(
            i -> i.mnemonic().equals("vpmulld"));
        boolean hasXor = snippet.instructions().stream().anyMatch(
            i -> i.mnemonic().equals("vpxor"));
        boolean hasSignExt = snippet.instructions().stream().anyMatch(
            i -> i.mnemonic().equals("vpmovsxbd"));
        boolean hasTruncate = hasShlSarPair(snippet);

        if (hasSignExt && hasMul && hasXor && hasTruncate) {
            // Full XorByte pattern
            sb.append("            // Sign-extend bytes, multiply, truncate to byte, XOR-reduce\n");
            if (inputRegs.size() >= 2) {
                sb.append("            int a = signExtByte(").append(inputRegs.get(0)).append("[i]);\n");
                sb.append("            int b = signExtByte(").append(inputRegs.get(1)).append("[i]);\n");
                sb.append("            int product = a * b;\n");
                sb.append("            int truncated = signExtByte(product);\n");
                sb.append("            result[i] = truncated ^ a;\n");
            }
        } else if (hasSignExt && hasMul) {
            sb.append("            // Sign-extend bytes and multiply\n");
            sb.append("            result[i] = signExtByte(a[i]) * signExtByte(b[i]);\n");
        } else {
            sb.append("            // (computation — see literal view for details)\n");
        }

        sb.append("        }\n\n");
        sb.append("        return result;\n");
    }

    private static void emitAArch64Explained(StringBuilder sb, AssemblySnippet snippet) {
        var inputRegs = collectAArch64InputRegisters(snippet);

        sb.append("    public static int[] run(");
        for (int i = 0; i < inputRegs.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("int[] ").append(inputRegs.get(i));
        }
        sb.append(") {\n");

        int lanes = 4; // aarch64 NEON .4s
        sb.append("        // Vectorized computation over ").append(lanes).append(" NEON lanes\n");
        sb.append("        int[] result = new int[").append(lanes).append("];\n\n");
        sb.append("        for (int i = 0; i < ").append(lanes).append("; i++) {\n");

        boolean hasMul = snippet.instructions().stream().anyMatch(
            i -> i.mnemonic().equals("mul") || i.mnemonic().equals("mla"));
        boolean hasEor = snippet.instructions().stream().anyMatch(
            i -> i.mnemonic().equals("eor3"));
        boolean hasSshll = snippet.instructions().stream().anyMatch(
            i -> i.mnemonic().equals("sshll"));

        if (hasSshll && hasMul && hasEor) {
            sb.append("            // Sign-extend bytes, multiply-accumulate, truncate, XOR-reduce\n");
            if (inputRegs.size() >= 2) {
                sb.append("            int a = signExtByte(").append(inputRegs.get(0)).append("[i]);\n");
                sb.append("            int b = signExtByte(").append(inputRegs.get(1)).append("[i]);\n");
                sb.append("            int product = a * b;\n");
                sb.append("            int truncated = signExtByte(product);\n");
                sb.append("            result[i] = truncated ^ a;\n");
            }
        } else {
            sb.append("            // (computation — see literal view for details)\n");
        }

        sb.append("        }\n\n");
        sb.append("        return result;\n");
        sb.append("    }\n");

        sb.append('\n');
        sb.append("    /** Sign-extend a byte value (equivalent to sshll .8b→.8h→.4s). */\n");
        sb.append("    private static int signExtByte(int unsignedByte) {\n");
        sb.append("        return (byte) unsignedByte;\n");
        sb.append("    }\n");

        sb.append('\n');
        sb.append("    public static void main(String[] args) {\n");
        sb.append("        int[] a = {1, 255, 127, 128};\n");
        sb.append("        int[] b = {10, 20, 30, 40};\n");
        sb.append("        int[] result = run(a, b);\n");
        sb.append("        System.out.print(\"Result: [\");\n");
        sb.append("        for (int i = 0; i < result.length; i++) {\n");
        sb.append("            if (i > 0) System.out.print(\", \");\n");
        sb.append("            System.out.print(result[i]);\n");
        sb.append("        }\n");
        sb.append("        System.out.println(\"]\");\n");
        sb.append("    }\n");
    }

    // --- Helpers ---

    private static List<String> collectInputRegisters(AssemblySnippet snippet) {
        var inputs = new LinkedHashSet<String>();
        var written = new HashSet<String>();
        for (var insn : snippet.instructions()) {
            if (insn.mnemonic().equals("vmovq") && insn.operands().getFirst() instanceof Operand.Memory) {
                String dst = ((Operand.Register) insn.operands().get(1)).name();
                inputs.add(dst);
                written.add(dst);
            } else if (insn.mnemonic().equals("vpmovsxbd")) {
                String src = ((Operand.Register) insn.operands().get(0)).name();
                if (!written.contains(src)) inputs.add(src);
            }
        }
        return inputs.stream().toList();
    }

    private static List<String> collectAArch64InputRegisters(AssemblySnippet snippet) {
        return snippet.instructions().stream()
            .filter(i -> i.mnemonic().equals("ldr")
                && i.operands().getFirst() instanceof Operand.Register r
                && r.name().startsWith("s"))
            .map(i -> ((Operand.Register) i.operands().getFirst()).name())
            .distinct()
            .toList();
    }

    private static boolean hasShlSarPair(AssemblySnippet snippet) {
        boolean hasShl = false, hasSar = false;
        for (var insn : snippet.instructions()) {
            if (insn.mnemonic().equals("vpslld")) hasShl = true;
            if (insn.mnemonic().equals("vpsrad")) hasSar = true;
        }
        return hasShl && hasSar;
    }
}
